title: NMB-lite
baseurl: "/NMB-lite"
permalink: pretty
markdown: kramdown
theme: just-the-docs
color_scheme: dark

# Plugins
plugins:
  - jekyll-feed


just_the_docs:
  aux_links:
    "Source on GitHub": "https://github.com/fancyc-bsi/NMB-lite"
  search_enabled: true
  search_label: 'Search the docs...'
  color_scheme: dark
